version: '3.8'

services:
  backend:
    image: my-backend-image:latest
    ports:
      - "8081:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: # You need to specify a password here
    networks:
      - app-network 

  frontend:
    image: my-frontend-image:latest
    ports:
      - "80:80"
    networks:
      - app-network  

  mysql:
    image: mysql:5.7
    ports:
      - "3333:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Note that the value should be a string
      MYSQL_DATABASE: devops
    volumes:
      - mysql_data:/mysql_data
    networks:
      - app-network  

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge  