version: '3.8'

services:
  backend:
    image: islemzouuuu/my-backend-image:latest
    ports:
      - "8081:8082"
    restart: always 
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: # You need to specify a password here
    networks:
      - app-network 

  frontend:
    image: islemzouuuu/my-angular-app
    ports:
      - "80:80"
    restart:  always
    depends_on:
      - backend
    networks:
      - app-network
      - frontend

  mysql:
    image: mysql:5.7
    ports:
      - "3333:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Note that the value should be a string
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD:
    volumes:
      - mysql_data:/mysql_data
    networks:
      - app-network  

volumes:
  mysql_data:

networks:
  app-network:
  frontend:  
