version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: devops-db
    ports:
      - "3306:3306"  # Map host port 3306 to container port 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: devops
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - my-network

  spring:
    image: islemzouuuu/my-backend-image:latest
    container_name: spring-back-project
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - mysql
    networks:
      - my-network
    volumes:
      - ./backend-data:/app/data

  angular:
    image: islemzouuuu/my-angular-app
    container_name: angular-front-project
    ports:
      - "80:80"
    depends_on:
      - spring
    networks:
      - my-network
    volumes:
      - ./frontend-data:/app/dist

networks:
  my-network:
